server:
  port: 8083
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/notification-service
    username: root
    password: Seamless
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update